### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by orschiro** [tizonia/tizonia-openmax-il#393]
Hello all, 

Is there already any way to run tizonia on Ubuntu 18.04?

Thank you!

**Comment by juanrubio** [comment]
Hi!,

There are no official binaries just yet, since 18.04 will come out next year. But Tizonia can be built from source, if you are up to the challenge and have a bit of time in your hands.

Any of the methods outlined here would work:
https://github.com/tizonia/tizonia-openmax-il/blob/master/BUILDING.md#building-from-source

**Comment by orschiro** [comment]
Thanks for your quick reply!

I may give these a try.

**Comment by juanrubio** [comment]
Sure, if you encounter any issues, just drop a line here!.

**Comment by vervaekejonathan** [comment]
Building it on 17.10, I'm getting this issue:

`bin/mkdir -p '/home/**/tizonia/lib/pkgconfig'
 /usr/bin/install -c -m 644 libtizplatform.pc '/home/**/tizonia/lib/pkgconfig'
Making install in rm
Making install in tizrmd
Making install in dbus
generating code for interface com.aratelia.tiz.tizrmif...
generating code for interface com.aratelia.tiz.tizrmif...
 /bin/mkdir -p '/home/**/tizonia/share/dbus-1/services'
 /bin/mkdir -p '/home/**/tizonia/include/tizonia'
 /usr/bin/install -c -m 644 com.aratelia.tiz.rm.service '/home/**/tizonia/share/dbus-1/services'
 /usr/bin/install -c -m 644 tizrmtypes.h tizrmd-dbus.hh tizrmproxy-dbus.hh '/home/**/tizonia/include/tizonia'
Making install in data
-e Populating /home/**/tizonia/tizonia-openmax-il/rm/tizrmd/data/tizrm.db using /home/**/tizonia/tizonia-openmax-il/rm/tizrmd/data/tizonia-rm-db-initial.sql3...
-e Done.
 /bin/mkdir -p '/home/**/tizonia/bin'
 /bin/mkdir -p '/home/**/tizonia/share/tizrmd'
 /usr/bin/install -c tizonia-rm-db-dump.sh tizonia-rm-db-generate.sh '/home/**/tizonia/bin'
 /usr/bin/install -c -m 644 tizonia-rm-db-initial.sql3 tizrm.db '/home/**/tizonia/share/tizrmd'
Making install in src
  CXX      tizrmd-tizrmd.o
  CXX      tizrmd-tizrmdb.o
In file included from /usr/include/dbus-c++-1/dbus-c++/server.h:34:0,
                 from /usr/include/dbus-c++-1/dbus-c++/dbus.h:33,
                 from tizrmd.hpp:46,
                 from tizrmd.cpp:43:
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h: In static member function ‘static void DBus::Threading<Mx, Cv>::init()’:
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h:262:5: error: no matching function for call to ‘_init_threading(DBus::Mutex* (&)(), void (&)(DBus::Mutex*), void (&)(DBus::Mutex*), void (&)(DBus::Mutex*), DBus::CondVar* (&)(), void (&)(DBus::CondVar*), void (&)(DBus::CondVar*, DBus::Mutex*), bool (&)(DBus::CondVar*, DBus::Mutex*, int), void (&)(DBus::CondVar*), void (&)(DBus::CondVar*))’
     );
     ^
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h:247:13: note: candidate: void DBus::_init_threading()
 void DXXAPI _init_threading();
             ^~~~~~~~~~~~~~~
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h:247:13: note:   candidate expects 0 arguments, 10 provided
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h:249:13: note: candidate: void DBus::_init_threading(DBus::MutexNewFn, DBus::MutexFreeFn, DBus::MutexLockFn, DBus::MutexUnlockFn, DBus::CondVarNewFn, DBus::CondVarFreeFn, DBus::CondVarWaitFn, DBus::CondVarWaitTimeoutFn, DBus::CondVarWakeOneFn, DBus::CondVarWakeAllFn) <near match>
 void DXXAPI _init_threading(
             ^~~~~~~~~~~~~~~
/usr/include/dbus-c++-1/dbus-c++/dispatcher.h:249:13: note:   conversion of argument 3 would be ill-formed:
Makefile:479: recept voor doel 'tizrmd-tizrmd.o' is mislukt
make[4]: *** [tizrmd-tizrmd.o] Fout 1
`

Posting it here since this probably will also affect 18.04, since the internet tells me this has to do with a GCC update.

**Comment by juanrubio** [comment]
Hi!,
I see. It's strange though. 17.10 shipped with gcc 7.2 (https://launchpad.net/ubuntu/artful/+source/gcc-7) and tizonia builds fine with 7.2 on Arch distros. So I'm thinking that there must be something else going on.

I'll have a look.

**Comment by juanrubio** [comment]
I believe there has been some blackguard-incompatible change somewhere in DBUS, and possibly libdbuscxx has not been updated to absorve it... It is just a theory, I have not investigated further yet...

**Comment by juanrubio** [comment]
It's compiler related:
https://sourceforge.net/p/dbus-cplusplus/patches/18/

**Comment by juanrubio** [comment]
I've been looking around and it seems that this dbus-c++ fork seems to contain a number of fixes that would allow Tizonia to build correctly in 17.10 and 18.04
https://github.com/pkgw/dbus-cplusplus

Next step is to asses whether to embed this fork in Tizonia or perhaps try to move to another C++-based DBUS option altogether. Tough choice!

**Comment by juanrubio** [comment]
Closing this issue. Tizonia now builds and runs correctly in Ubuntu 18.04. 

See #413.

**Comment by orschiro** [comment]
@juanrubio thank you for the fix! :-)
